
modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/MehVahdJukaar/wood_good/issues" #optional

[[mods]] #mandatory

modId="wood_good" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Wood Good" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/wood_good" #optional

logoFile="logo.png" #optional

credits="" #optional

authors="MehVahdJukaar" #optional

description='''Ultimate Wood Compat Mod'''

itemIcon="minecraft:oak_planks" #catalogue icon


[[dependencies.furniture_thingy]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.furniture_thingy]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.furniture_thingy]]

    modId="selene"
    mandatory=true
    versionRange="[1.18.2-1.15.6,]"
    ordering="AFTER"
    side="BOTH"


